### ISSUE TITLE
Custom drag layer results in occasional artifacts (drag item flashes in random location)

### ISSUE THREAD

**Issue by stevenkkim** [react-dnd/react-dnd#1427]
**Describe the bug**
Dragging and dropping items with custom drag layer results in occasional artifacts (flashing drag item in random screen location). Most of the time there is no artifact, but I keep dragging and dropping, it does eventually happen. I'm using on Chrome 75 on Windows 10. 

This occurs in both the [custom drag layer example](http://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer), and also in my react app.

**To Reproduce**
1. Go to [http://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer](http://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer)
2. Drag and drop repeatedly
3. See error

**Expected behavior**
No artifacts or random flashes of dragged item on drag/drop.

**Screenshots**
![React DnD - Google Chrome 2019-06-25 09-12-08](https://user-images.githubusercontent.com/4841651/60116144-557b2600-972c-11e9-99ff-460b3220623b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75

**Additional context**
This may be related to [Issue 929](https://github.com/react-dnd/react-dnd/issues/929). I tried using the proposed solution of applying a css animation, but it did not fix the bug for me.

**Comment by qtsd** [comment]
Have you tried the `will-change: transform;` css property ?

**Comment by stevenkkim** [comment]
I just tried your suggestion of applying `will-change: transform;` css to
the custom dray layer, but it unfortunately doesn't solve the problem for
me.

**Comment by darthtrevino** [comment]
There was an issue introduced in 7.4.5 where drag previews were being detached too aggressively. This should be fixed in 9.0.1, but let me know if you still run into it.

**Comment by stevenkkim** [comment]
Hi @darthtrevino , I'm still having artifacting issues with react-dnd in version 9.34 and 9.4.0

If you go to the custom drag layer example here:
https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/02-drag-around/custom-drag-layer

Then in CustomDragLayer.jsx insert after line 29 `console.log(x + ', ' + y)`

Then drag an item and look at the console log, you'll get something like this:

89, 29 
89, 29 
89, 29 
8, 11 
8, 11 
89, 40 
89, 49 
88, 52 
88, 55 
88, 59 
88, 61 
88, 66 
88, 68 
89, 71 

You can see in the 4th and 5th lines the x,y coordinates of 8,11 which cause the artifacting to occur. For me, this console output always happens, although most of the time I think it happens so fast that perhaps the browser isn't rendering those coordinates and so the user only sees it occasionally. But for me, the console log shows these coordinate jumps every time.

**Comment by stevenkkim** [comment]
For anyone interested, this appears to be a problem with react-dnd-html5-backend.
When using react-dnd-touch-backend, the problem does not occur.
So for the time being, I am going to try using react-dnd-touch-backend:

```
import DnDHtml5Backend from 'react-dnd-html5-backend';

<DndProvider backend={DnDTouchBackend} options={{ enableTouchEvents: false, enableMouseEvents: true }}>
    {/* code */}
</DndProvider>
```

I'm a bit worried since the documentation says:

enableMouseEvents(default: false)
A flag indicating whether to enable click-based event processing.
NOTE: This is buggy due to the difference in touchstart/touchend event propagation compared to mousedown/mouseup/click.

https://react-dnd.github.io/react-dnd/docs/backends/touch

I guess I'll find out soon exactly how buggy this is.

**Comment by Simon-44** [comment]
Hello,

I'm in React-DnD version 5.0.0 and because of this glitch, I have to check differenceFromInitialOffset during drag'n drop and prevent the "hover" effect from rendering if it seems the cursor coordinates are glitching. That is a big performance issue.

Since @stevenkkim says it's a problem in react-dnd-html5-backend, I was wondering if it was fixed in the latest versions?

Thanks
