### ISSUE TITLE
Wrong dragPreview in Chrome

### ISSUE THREAD

**Issue by ravinderk** [react-dnd/react-dnd#1608]
**Describe the bug**
I see two different dragPreview for the same code. I find that results are fine as expected but on Chrome I see two issues:
1. dragPreview height is not right.
2. I am seeing a white color in the background.

**Google Chrome**
![d2GjfYizYL](https://user-images.githubusercontent.com/1784821/69253962-7bbdc880-0bdb-11ea-9dbd-e97171322eaf.gif)

**Firefox**
![j1fxz8Yywn](https://user-images.githubusercontent.com/1784821/69253972-811b1300-0bdb-11ea-8e82-aba439c40c00.gif)

**Code samples:**

**File 1**
```
import React from 'react';
import {__} from '@wordpress/i18n';
import {DndProvider} from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';
import update from 'immutability-helper';
import Legend from '../Legend/Legend';
import Header from './Header';
import RowWithDragHandle from './RowWithDragHandle';
import AddRowButton from './AddRowButton';

function uniqid() {
    // Math.random should be unique because of its seeding algorithm.
    // Convert it to base 36 (numbers + letters), and grab the first 9 characters
    // after the decimal.
    return `_${Math.random()
        .toString(36)
        .substr(2, 9)}`;
}

export default function DonationAmounts() {
    const [row, setRow] = React.useState([{id: uniqid()}]);

    const handleAddRow = () => {
        setRow([...row, {id: uniqid()}]);
    };

    const handleDeleteRow = rowID => {
        const temp = row.filter(item => rowID !== item.id);
        setRow(temp);
    };

    const moveCard = React.useCallback(
        (dragIndex, hoverIndex) => {
            const dragRow = row[dragIndex];
            setRow(
                update(row, {
                    $splice: [[dragIndex, 1], [hoverIndex, 0, dragRow]],
                })
            );
        },
        [row]
    );

    return (
        <div className="text-xs">
            <fieldset>
                <Legend instructions={__('You can create list of amounts for donation', 'givewp-campaigns')}>
                    {__('Amounts', 'givewp-campaigns')}
                </Legend>
                <div className="mb-7 rounded border border-campaign-white-300 overflow-hidden">
                    <Header />
                    <div className="px-3 pt-3 text-campaign-gray-600">
                        <DndProvider backend={HTML5Backend}>
                            {row.map(({id}, index) => (
                                <RowWithDragHandle
                                    key={id}
                                    id={id}
                                    index={index}
                                    onDeleteRow={handleDeleteRow}
                                    showCloseButton={row.length > 1}
                                    moveCard={moveCard}
                                />
                            ))}
                        </DndProvider>
                    </div>
                </div>
            </fieldset>
            <AddRowButton onAddRow={handleAddRow} />
        </div>
    );
}

// @todo: set focus when add new row
```

**File 2**
```
import React from 'react';
import {__} from '@wordpress/i18n';
import PropTypes from 'prop-types';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faArrowsAlt, faDollarSign} from '@fortawesome/free-solid-svg-icons';
import {useDrag, useDrop} from 'react-dnd';
import CloseButton from './CloseButton';
import NumberInput from '../NumberInput/NumberInput';
import TextInput from '../TextInput/TextInput';

const RowWithDragHandle = ({id, index, onDeleteRow, showCloseButton, moveCard}) => {
    const ref = React.useRef(null);
    const [, drop] = useDrop({
        accept: 'card',
        hover(item, monitor) {
            if (!ref.current) {
                return;
            }
            const dragIndex = item.index;
            const hoverIndex = index;
            // Don't replace items with themselves
            if (dragIndex === hoverIndex) {
                return;
            }
            // Determine rectangle on screen
            const hoverBoundingRect = ref.current.getBoundingClientRect();
            // Get vertical middle
            const hoverMiddleY = (hoverBoundingRect.bottom - hoverBoundingRect.top) / 2;
            // Determine mouse position
            const clientOffset = monitor.getClientOffset();
            // Get pixels to the top
            const hoverClientY = clientOffset.y - hoverBoundingRect.top;
            // Only perform the move when the mouse has crossed half of the items height
            // When dragging downwards, only move when the cursor is below 50%
            // When dragging upwards, only move when the cursor is above 50%
            // Dragging downwards
            if (dragIndex < hoverIndex && hoverClientY < hoverMiddleY) {
                return;
            }
            // Dragging upwards
            if (dragIndex > hoverIndex && hoverClientY > hoverMiddleY) {
                return;
            }
            // Time to actually perform the action
            moveCard(dragIndex, hoverIndex);
            // Note: we're mutating the monitor item here!
            // Generally it's better to avoid mutations,
            // but it's good here for the sake of performance
            // to avoid expensive index searches.
            // eslint-disable-next-line no-param-reassign
            item.index = hoverIndex;
        },
    });

    const [{isDragging}, drag] = useDrag({
        item: {type: 'card', id, index},
        collect: monitor => ({
            isDragging: monitor.isDragging(),
        }),
    });

    const opacity = isDragging ? 0 : 1;

    drag(drop(ref));

    return (
        <div className="mb-3 flex items-center" style={{opacity}} ref={ref}>
            <div className="pr-3">
                <NumberInput
                    name="donationAmounts[][amount]"
                    label={__('Amount', 'givewp-campaigns')}
                    labelHidden
                    min={0}
                    value={10}
                    prefix={<FontAwesomeIcon icon={faDollarSign} />}
                    onChange={() => {}}
                    className="pl-1 pr-1 leading-tight"
                    style={{maxWidth: '55px'}}
                />
            </div>
            <div className="pr-3">
                <TextInput
                    name="donationAmounts[][text]"
                    label={__('Text', 'givewp-campaigns')}
                    labelHidden
                    min={0}
                    value="demo text"
                    onChange={() => {}}
                    className="leading-tight"
                />
            </div>
            <div className="cursor-move pr-3">
                <FontAwesomeIcon icon={faArrowsAlt} className="text-gray-400" />
            </div>
            {showCloseButton && <CloseButton onClick={() => onDeleteRow(id)} />}
        </div>
    );
};

RowWithDragHandle.propTypes = {
    id: PropTypes.string.isRequired,
    index: PropTypes.number.isRequired,
    onDeleteRow: PropTypes.func.isRequired,
    showCloseButton: PropTypes.bool.isRequired,
    moveCard: PropTypes.func.isRequired,
};

export default RowWithDragHandle;

```

**Expected Behavior**
I expect the same behavior on Firefox and Google Chrome when drag row.

- OS: IOS
- Browser Google Chrome 78

```
"react-dnd": "^9.4.0",
"react-dnd-html5-backend": "^9.4.0",
```

**Related**
I did not see any positive response on the `closed` issue that's why I am creating a new issue.
ref: https://github.com/react-dnd/react-dnd/issues/832

**Comment by ravinderk** [comment]
It works fine in one out of ten Goggle Chrome browser refresh. You can see white background which I mentioned in the issue description.

![JrJpP2jyFC](https://user-images.githubusercontent.com/1784821/69256282-3e5b3a00-0bdf-11ea-9b81-4a2a89044a16.gif)

**Comment by SnowblindFatal** [comment]
I have also encountered this issue, though with slightly different symptoms.

On firefox things work fine:
![firefox items](https://user-images.githubusercontent.com/1068367/70239742-85673480-1774-11ea-8032-332340b91171.gif)

On chrome weirdly the drag preview additionally shows all the items preceding the previous one:
![chrome items](https://user-images.githubusercontent.com/1068367/70239747-8a2be880-1774-11ea-8381-933eac003a60.gif)


I can't unfortunately paste an easy code for reproduction, but my list items have absolute position and a top style to determine their position. Maybe this has something to do with the issue?

**Comment by SnowblindFatal** [comment]
Actually I just tested using relative positioning and the issue was solved. So I guess absolute positioned elements cause issues in Chrome.

**Comment by yume-chan** [comment]
The white background is added by Chrome, maybe to optimize performance (get the preview image from composited graphic buffer?).

I learned from SortableJS that adding a `transform: translateZ(0)` to the drag source can workaround this problem. Maybe Chrome now creates an extra layer for your element.

**Comment by acroyear** [comment]
As noted on the other chrome bug, the transform leads to still having some inconsistencies in the ghost view being quite a bit offset from the mouse.  Also, my views are all normal inline, block, or inline-block - no relative nor absolute positioning. Just normal material-ui ListItems.

**Comment by Gregoirevda** [comment]
For material-ui `ListItem` component, not adding the `button` prop fixes the issue

**Comment by acroyear** [comment]
i'll take a look that way, but i also kind of don't want to lose accessibility by having on-clicks that aren't on anchor/button tags and so can't be tabbed to.

**Comment by MasterRoshan** [comment]
I ran into this issue, and in my case it ended up being bad css, I had a child element with a height greater than the parent element.

Steps to reproduce:
- create a draggable element with dimensions 200x200
- create a child of that element with dimensions 200x600
- the result will be an element that appears to be 200x200, but the drag preview image will be 200x600

Hope this helps some people

**Comment by joshuahiggins** [comment]
The child element size issue is what I'm experiencing. In my case, the child element is a scrollable container. The preview is applied inconsistently. Sometimes it drags just the displayed element, sometimes it drags the displayed and the next element, and sometimes it drags just the displayed element, but it offsets the height by the overflow size of the child (ignoring the true child element size). This is the same code and no change... It's just kind of random which happens.

**Comment by edcaron** [comment]
> I ran into this issue, and in my case it ended up being bad css, I had a child element with a height greater than the parent element.
> 
> Steps to reproduce:
> 
> * create a draggable element with dimensions 200x200
> * create a child of that element with dimensions 200x600
> * the result will be an element that appears to be 200x200, but the drag preview image will be 200x600
> 
> Hope this helps some people

That worked for me. I had an child element bigger than the drag ref parent so the size when dragging was the size of the biggest (the child).
