### ISSUE TITLE
Dragover events won't fire in Chrome

### ISSUE THREAD

**Issue by cc2victoria** [react-dnd/react-dnd#688]
I got a problem with react-dnd.  I can't run this [tutorial-app](http://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html) in my Chrome. The dragover events doen't seem to be triggered. But it works well with Firefox and Sarfri. I got confused. Here's the version of my Chrome: `Version 56.0.2924.87 (64-bit)`.  
What is the reason for that and how to fix it?

**Comment by theTechie** [comment]
looks like its broken. I don't see it working in Firefox nor Safari.  
@cc2victoria - are you able to move the `horse` to different boxes? (in Firefox and Safari)

**Comment by suhaotian** [comment]
Mine's same version chrome work well
![image](https://cloud.githubusercontent.com/assets/6512574/23744591/cbc4926e-04ef-11e7-9926-b4944c737210.png)

**Comment by cc2victoria** [comment]
@theTechie  Yes, I can move horse to different boxes in FireFox.

**Comment by theTechie** [comment]
Yes. Looks like it's fixed now. It should also work in Chrome now!

Please close this if it's no more a issue.

**Comment by cc2victoria** [comment]
@theTechie Sorry, it still doesn't work in my Chrome or my colleague's. I can't even see the horse picture or the color in my chessboard when I drag the white horse.

**Comment by theTechie** [comment]
Something very strange. We are using the exact same version of Chrome and its working for me.

Could you check for any errors in the browser console ? 
It will be helpful if you can share a GIF when its breaking for you.

**Comment by cc2victoria** [comment]
@theTechie There's no error in the browser console. But with you proposal, I suddenly got it. When I drag the horse, something else showed up in my page.

I have installed a extension named [Dragdis](https://chrome.google.com/webstore/detail/dragdis/fiekimdgbphfmnlbiahcfdgcipcopmep) in my Chrome. And it seems to have some conflicts with react-dnd. I think it may be the horse picture which fired both. So I removed the Dragdis extension. Now, the demo works well in my chrome as well as my own project.

You are very heplpful, thank you very much!
