### ISSUE TITLE
Firefox verison 52.0 on Windows 7 : 'Error: cannot call hover while not dragging' 

### ISSUE THREAD

**Issue by nish1013** [react-dnd/react-dnd#714]
When you 'drop' (i.e. let go of the mouse), Firefox console reports 'Error: cannot call hover while not dragging'

**Comment by anilreddykatta** [comment]
@nish1013 Can you provide sample code?

**Comment by heyimalex** [comment]
I'm getting the same issue in FF 54.0a2, and can reproduce on the [native files demo](http://react-dnd.github.io/react-dnd/examples-other-native-files.html). It fails with this error frequently, probably three times more often than it succeeds. Just from playing around with it I haven't discovered any consistent conditions for reproducing. Definitely only effects the native drag and drop though. I'll try and dig in more.

**Comment by heyimalex** [comment]
Uggh well it looks like this issue is already fixed via #713 and we're just waiting for a release.

**Comment by andrewQwer** [comment]
Has this fix been released? I still can reproduce it on (Examples)[https://react-dnd.github.io/react-dnd/examples-other-native-files.html] page https://www.screencast.com/t/kICFl4eN

**Comment by andrewQwer** [comment]
Just tested with HTML5Backedn 2.4.0 and react-dnd@2.4.0 - issue still reproduced :(

**Comment by samsch** [comment]
I experienced this issue in Firefox on Linux (54.0 64bit, Xubuntu 16.10 (I know, I need to update)).

In my case I was also calling setState the synchronous flow from spec drop(). On a hunch that it may be due to the process here being slow and properties of or the monitor itself being destroyed before another handler is called, I cached `monitor.getItem().files` in drop, and then used that in a setTimeout(..., 0) handler. I haven't seen the issue with this workaround in place.

```js
DropTarget(NativeTypes.FILE, fileTarget ...

// Where fileTarget is defined:
const fileTarget = {
  drop(props, monitor) {
    const files = monitor.getItem().files;
    window.setTimeout(() => {
      props.onDrop(files);
    }, 0);
  },
};
```

**Comment by samsch** [comment]
Up to Firefox version 55 and still seeing this issue.

**Comment by heyimalex** [comment]
I don't really remember the issue, but the demo page doesn't appear to be affected on FF 57.0b3.

**Comment by theobarberbany** [comment]
Am also getting this error on Firefox 57.0b9

**Comment by danii1** [comment]
Can reliably reproduce bug when dragging files from another window to Firefox, if FF don't get focus there are no bugs(first 2 drags), but if you drag files and bring focus to FF you'll get this bug, fix with setTimeout does nothing, FF 57.0
![dnd-bug](https://user-images.githubusercontent.com/5345961/32818792-f7f4ba26-c9f7-11e7-9c71-a9ce6ddf7b81.gif)

**Comment by janpe** [comment]
I am also seeing the same error. Any news on this?
